# Generated by Django 5.2.3 on 2025-06-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descripiton',
            new_name='description',
        ),
    ]
